require: rubocop-rspec
AllCops:
  Exclude:
    - 'lib/templates/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/support/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'webpack/**/*'
    - 'public/**/*'
    - 'config/**/*'
    - 'Guardfile'
    - 'node_modules/**/*'
    - lib/tasks/auto_annotate_models.rake

LineLength:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
RSpec/ExampleLength:
  Max: 90
