language: ruby
cache: bundler
rvm:
  - 2.3.1
services:
  - postgresql
before_script:
  - psql -c 'create database gse_test;' -U postgres
  - RAILS_ENV=test bin/setup
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script:
  - CI=true RAILS_ENV=test bundle exec rspec spec/
  - CI=true RAILS_ENV=test bundle exec rubocop
