language: ruby
cache: bundler
rvm:
  - 2.3.1
services:
  - postgresql
before_script:
  - psql -c 'create database gse_test;' -U postgres
  - bin/setup
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec spec/
  - bundle exec rubocop
